name: bloc_getx_boilerplate
description: BLoC with GetX boilerplate flutter

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Core
  get: ^4.3.8
  equatable: ^2.0.3
  flutter_bloc: ^7.3.3

  # Notification
  flutter_local_notifications: ^9.1.2
  firebase_messaging: ^11.1.0

  #SignIn social
  firebase_core: ^1.10.0
  firebase_auth: ^3.2.0
  google_sign_in: ^5.2.1
  flutter_facebook_auth: ^3.5.6
  sign_in_with_apple: ^3.2.0

  #Network
  dio: ^4.0.3
  logger: ^1.1.0
  connectivity_plus: ^2.0.3

  hive: ^2.0.4
  rxdart: ^0.27.2
  path_provider: ^2.0.7
  responsive_builder: ^0.4.1
  fluttertoast: ^8.0.8
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/roboto/Roboto-Black.ttf
          weight: 800
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 600
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 200
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 100
